---
# tasks file for httpd
- name: Gather minimal facts subset
  setup:
    gather_subset: min

- name: RHEL based installation
  block:
    - name: Install httpd
      yum:
        name: httpd
        state: present
      become: yes

    - name: Start/enable service
      service:
        name: httpd
        state: started
        enabled: yes
      become: yes
  when: ansible_distribution in ['RedHat', 'CentOS']

- name: Debian based installation
  block:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      become: yes

    - name: Start/enable service
      service:
        name: apache2
        state: started
        enabled: yes
      become: yes
  when: ansible_distribution == 'Debian'

- name: Deploy "custom" index file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0644
  become: yes

- name: Open firewall
  firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes
  become: yes
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
